apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh2vm-demo-deploy
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: cluster.domain
          value: <here-goes-your-openshift-cluster-domain>
        - name: github.pat
          value: <here-goes-your-github-pat>
        - name: rhn.username
          value: <here-goes-your-redhat-customer-portal-username>
        - name: rhn.password
          value: <here-goes-your-redhat-customer-portal-password>
        - name: rhn.poolId
          value: <here-goes-your-ansible-subscription-poolId>
        - name: automationhub.apiToken
          value: <here-goes-your-redhat-automationhub-apiToken>
        - name: rhn.clientId
          value: <here-goes-your-redhat-customer-portal-clientId>
        - name: rhn.clientSecret
          value: <here-goes-your-redhat-customer-portal-clientSecret>
    path: rhdh2vm-demo-deploy
    repoURL: 'https://github.com/sgutierr/rhdhdemotemplate.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true