kind: ConfigMap
apiVersion: v1
metadata:
  name: '{{ .Values.developerhub.dynamicPluginsConfigMapName }}'
  namespace: '{{ .Values.developerhub.namespaceName }}'
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  dynamic-plugins.yaml: |
    includes:
    - dynamic-plugins.default.yaml
    plugins:
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-security-insights
    - disabled: false
      package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic
    - disabled: false
      integrity: sha512-VuH3tCeDwBgS0hrXec1F3VMFsLnYePWJwP2Wo8WyjrOY7G0CkYBLM0eyYZT4DFp/EpzepFPbztfKZ95fCJ3I1g==
      package: '@red-hat-developer-hub/backstage-plugin-dynamic-home-page'       
    - disabled: false
      package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-community-plugin-topology
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
    - disabled: true
      package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-utils-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-techdocs
    - disabled: true
      package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar
    - disabled: true
      package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar-backend-dynamic     
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd  
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import
      disabled: false
      pluginConfig:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-bulk-import:
              # Start of fab config
              mountPoints:
                - mountPoint: global.floatingactionbutton/config
                  importName: BulkImportPage 
                  config:
                    slot: 'page-end'
                    icon: <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#e8eaed"><g><rect fill="none" height="24" width="24"/></g><g><path d="M11,7L9.6,8.4l2.6,2.6H2v2h10.2l-2.6,2.6L11,17l5-5L11,7z M20,19h-8v2h8c1.1,0,2-0.9,2-2V5c0-1.1-0.9-2-2-2h-8v2h8V19z"/></g></svg>
                    label: 'Bulk import'
                    toolTip: 'Register multiple repositories in bulk'
                    to: /bulk-import/repositories
              # end of fab config
              appIcons:
                - name: bulkImportIcon
                  importName: BulkImportIcon
              dynamicRoutes:
                - path: /bulk-import/repositories
                  importName: BulkImportPage
                  menuItem:
                    icon: bulkImportIcon
                    text: Bulk import
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-floating-action-button
      disabled: false
      pluginConfig:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-global-floating-action-button:
              mountPoints:
                - mountPoint: application/listener
                  importName: DynamicGlobalFloatingActionButton
                - mountPoint: global.floatingactionbutton/config
                  importName: NullComponent 
                  config:
                    icon: github
                    label: 'Git'
                    toolTip: 'Github'
                    to: https://github.com/redhat-developer/rhdh-plugins
                - mountPoint: global.floatingactionbutton/config
                  importName: NullComponent 
                  config:
                    icon: '<svg viewBox="0 0 250 300" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid"><path d="M200.134 0l55.555 117.514-55.555 117.518h-47.295l55.555-117.518L152.84 0h47.295zM110.08 99.836l20.056-38.092-2.29-8.868L102.847 0H55.552l48.647 102.898 5.881-3.062zm17.766 74.433l-17.333-39.034-6.314-3.101-48.647 102.898h47.295l25-52.88v-7.883z" fill="#40B4E5"/><path d="M152.842 235.032L97.287 117.514 152.842 0h47.295l-55.555 117.514 55.555 117.518h-47.295zm-97.287 0L0 117.514 55.555 0h47.296L47.295 117.514l55.556 117.518H55.555z" fill="#003764"/></svg>'
                    label: 'Quay'
                    showLabel: true
                    toolTip: 'Quay'
                    to: 'https://quay.io'
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
      disabled: false
      pluginConfig:
        app:
          sidebar:
            search: false    
            settings: false  
        dynamicPlugins:
          frontend:
            default.main-menu-items: 
              menuItems:
                default.create:
                  title: ''
            red-hat-developer-hub.backstage-plugin-global-header: # the default enabled dynamic header plugin
              mountPoints:
                - mountPoint: application/header
                  importName: GlobalHeader
                  config:
                    position: above-main-content 
                - mountPoint: global.header/component
                  importName: SearchComponent
                  config:
                    priority: 100
                - mountPoint: global.header/component
                  importName: Spacer
                  config:
                    priority: 99
                    props:
                      growFactor: 0
                - mountPoint: global.header/component
                  importName: HeaderIconButton
                  config:
                    priority: 90
                    props:
                      title: Create...
                      icon: add
                      to: create
                - mountPoint: global.header/component
                  importName: SupportButton
                  config:
                    priority: 80
                - mountPoint: global.header/component
                  importName: NotificationButton
                  config:
                    priority: 70
                - mountPoint: global.header/component
                  importName: Divider
                  config:
                    priority: 50
                - mountPoint: global.header/component
                  importName: ProfileDropdown
                  config:
                    priority: 10
                - mountPoint: global.header/profile
                  importName: MenuItemLink
                  config:
                    priority: 100
                    props:
                      title: Settings
                      link: /settings
                      icon: manageAccounts
                - mountPoint: global.header/profile
                  importName: LogoutButton
                  config:
                    priority: 10                    