apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-frontend
  description: 'The Angular frontend for ${{values.component_id}} (${{values.description}})'
  annotations:
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    gitlab.com/project-slug: ${{values.gitlabGroup}}/${{values.repoName}}
    backstage.io/techdocs-entity: component:default/${{values.component_id}}-service
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
  tags:
    - typescript
    - angular
    - book
    - example
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://${{values.git_host}}/${{values.gitlabGroup}}/${{values.repoName}}?che-editor=che-incubator/che-code/latest&devfilePath=src/main/angular/.devfile-vscode.yaml
      title: OpenShift Dev Spaces
      icon: web
    - url: https://${{values.component_id}}-${{values.namespace}}${{values.cluster_id}}
      title: ${{values.component_id}} Frontend
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: idp-system-${{values.namespace}}
  consumesApis:
    - ${{values.component_id}}-api
  subcomponentOf: component:default/${{values.component_id}}-service
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: idp-system-${{values.namespace}}
  tags:
    - backstage
    - janus-idp
    - rhdh
    - book
spec:
  owner: ${{values.owner | dump}}
