apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '{{ .Values.keycloak.statefulSetName }}'
  namespace: '{{ .Values.keycloak.namespaceName }}'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:latest
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRES_PASSWORD
              value: '{{ .Values.keycloak.postgresPassword }}'
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: '{{ .Values.keycloak.postgresDb }}'
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: '{{ .Values.keycloak.namespaceName }}'  
spec:
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432