kind: Secret
apiVersion: v1
metadata:
  name: '{{ .Values.keycloak.tlsSecretName }}'
  namespace: '{{ .Values.keycloak.namespaceName }}'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  tls.crt: '{{ .Values.keycloak.crtFile | b64enc }}'
  tls.key: '{{ .Values.keycloak.keyFile | b64enc }}'
type: kubernetes.io/tls