kind: Secret
apiVersion: v1
metadata:
  name: '{{ .Values.keycloak.dbSecretName }}'
  namespace: '{{ .Values.keycloak.namespaceName }}'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  password: '{{ .Values.keycloak.postgresPassword | b64enc }}'
  username: '{{ .Values.keycloak.postgresUsername | b64enc }}'
type: Opaque