apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-service
  description: 'The Quarkus service for ${{values.component_id}} (${{values.description}})'
  annotations:
    argocd/app-name: ${{values.component_id}}-dev
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: ${{values.gitlabGroup}}/${{values.repoName}}
    janus-idp.io/tekton : ${{values.component_id}}
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
  tags:
    - java
    - quarkus
    - maven
    - book
    - example
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/dev-pipelines/ns/${{values.namespace}}/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://${{values.git_host}}/${{values.gitlabGroup}}/${{values.repoName}}?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: idp-system-${{values.namespace}}
  providesApis:
    - ${{values.component_id}}-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: idp-system-${{values.namespace}}
  tags:
    - rhdh
    - book
spec:
  owner: ${{values.owner | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id}}-api
  description: API surface exposed by the Quarkus service
  links:
    - url: https://${{values.component_id}}-${{values.namespace}}${{values.cluster_id}}/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://${{values.git_host}}/${{values.gitlabGroup}}/${{values.repoName}}/-/blob/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: idp-system-${{values.namespace}}
  definition:
    $text: ./src/main/resources/META-INF/openapi.yaml
