apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
  namespace: {{ .Values.developerhub.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded  
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]