---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    openshift.io/description: {{ .Values.developerhub.namespaceName }}
    openshift.io/display-name: {{ .Values.developerhub.namespaceName }}
  name: {{ .Values.developerhub.namespaceName }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.developerhub.operatorGroupName }}
  namespace: {{ .Values.developerhub.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.developerhub.subscriptionName }}
  namespace: {{ .Values.developerhub.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace