---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.gitlab.namespaceName }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.gitlab.operatorGroupName }}
  namespace: {{ .Values.gitlab.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{ .Values.gitlab.namespaceName }}
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gitlab-operator-kubernetes.gitlab-system: ''
  name: {{ .Values.gitlab.subscriptionName }}
  namespace: {{ .Values.gitlab.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitlab-operator-kubernetes
  source: certified-operators
  sourceNamespace: openshift-marketplace