apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.componentId }}
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"{{ .Values.app.applicationId }}:latest","namespace":"{{ .Values.app.namespace }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nodejs-template\")].image","pause":"false"}]
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"StatefulSet","name":"{{ .Values.app.componentId }}{{ne .Values.global.environment "" | ternary (list "-" .Values.global.environment | join "") "-dev" }}-postgresql"}]
  labels:
    {{- include "nodejs-template.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: idp-book-example
    app.openshift.io/runtime: nodejs
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nodejs-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backstage.labels" . | nindent 8 }}
        {{- include "nodejs-template.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nodejs-template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: DATABASE_URL
            value: "postgres://{{.Values.app.database.user}}:{{.Values.app.database.password}}@{{.Values.app.database.host}}{{ne .Values.global.environment "" | ternary (list "-" .Values.global.environment | join "") "-dev" }}-postgresql:{{.Values.app.database.port}}/{{.Values.app.database.catalog}}"
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.host}}/{{.Values.image.repository}}{{ne .Values.global.environment "" | ternary (list "-" .Values.global.environment | join "") "" }}/{{.Values.image.name}}:{{.Values.global.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
